FROM python:3.8.13

WORKDIR /client

COPY proto_web.proto ./

COPY requirements.txt /client

RUN pip3 install -r requirements.txt

RUN python3 -m grpc_tools.protoc -I./ --python_out=. --grpc_python_out=. ./proto_web.proto

ENV FLASK_APP=client.py
ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 9000
COPY . .
CMD ["flask", "run"]