version: '2'

services:
  cliente:
    container_name: cliente
    build: ./client
    restart: always
    ports: 
      - "9000"
    environment:
      FLASK_ENV: development
    depends_on:
      - postgresql
      - redis-master
      - redis-replica
      - redis-replica2
      - servidor
  servidor:
    container_name: servidor
    build: ./backend
    restart: always
    ports:
      - "50051"
    environment:
      FLASK_ENV: development
    depends_on:
      - postgresql
      - redis-master
      - redis-replica
      - redis-replica2
  postgresql:
    container_name: postgres
    restart: always
    image: docker.io/bitnami/postgresql:14
    networks:
      cont:
        ipv4_address: 172.20.1.2
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USER=${POSTGRES_USER}'
      - 'POSTGRESQL_DATABASE=${POSTGRES_DB}'
      - 'ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}'
      - 'POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}'
  redis-master:
    container_name: cachemain
    image: 'bitnami/redis:latest'
    networks:
      cont:
        ipv4_address: 172.20.1.3
    restart: always
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    command:
      [
        "redis-server",
        "--protected-mode no",
        "--maxmemory 2mb",
        "--maxmemory-policy",
        "allkeys-lru"
      ]
  redis-replica:
    container_name: cachereplica
    image: 'bitnami/redis:latest'
    networks:
      cont:
        ipv4_address: 172.20.1.4
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2mb --maxmemory-policy allkeys-lfu

  redis-replica2:
    container_name: cachereplica2
    image: 'bitnami/redis:latest'
    networks:
      cont:
        ipv4_address: 172.20.1.5
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2mb --maxmemory-policy allkeys-lfu

volumes:
  postgresql_data:
    driver: local
networks:
  cont:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
