version: '2'

services:
  postgresql:
    container_name: postgres
    restart: always
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USER=${POSTGRES_USER}'
      - 'POSTGRESQL_DATABASE=${POSTGRES_DB}'
      - 'ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}'
      - 'POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}'
  redis:
    container_name: cache1
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  
volumes:
  postgresql_data:
    driver: local
