version: '3.8'

services:
  postgresql:
    container_name: postgres
    image: bitnami/postgresql:12.10.0
    restart: always
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.2
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USER=${POSTGRES_USER}'
      - 'POSTGRESQL_DATABASE=${POSTGRES_DB}'
      - 'ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}'
      - 'POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}'
  cliente:
    container_name: cliente
    build: ./client
    restart: always
    ports: 
      - "9000"
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.10
    environment:
      FLASK_ENV: development
    depends_on:
      - postgresql
      - redis-master
      - redis-replica
      - redis-replica2
      - servidor
  servidor:
    container_name: servidor
    build: ./backend
    restart: always
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.8
    ports:
      - "50051:50051"
    environment:
      FLASK_ENV: development
    tty: true
    
    depends_on:
      - postgresql
      - redis-master
      - redis-replica
      - redis-replica2
  redis-master:
    container_name: cachemain
    image: 'bitnami/redis:latest'
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.3
    restart: always
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    command:
      [
        "redis-server",
        "--protected-mode no",
        "--maxmemory 2mb",
        "--maxmemory-policy",
        "allkeys-lru"
      ]
  redis-replica:
    container_name: cachereplica
    image: 'bitnami/redis:latest'
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.4
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2mb --maxmemory-policy allkeys-lfu

  redis-replica2:
    container_name: cachereplica2
    image: 'bitnami/redis:latest'
    # networks:
    #   cont:
    #     ipv4_address: 172.20.1.5
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2mb --maxmemory-policy allkeys-lfu

volumes:
  postgresql_data:
    driver: local
networks:
  default:
    driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.1.0/24
