version: '2'

services:
  postgresql:
    container_name: postgres
    restart: always
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USER=${POSTGRES_USER}'
      - 'POSTGRESQL_DATABASE=${POSTGRES_DB}'
      - 'ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}'
      - 'POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}'
  redis-master:
    container_name: cachemain
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    command:
      [
        "redis-server",
        "--protected-mode no"
      ]
  redis-replica:
    container_name: cachereplica
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
  redis-replica2:
    container_name: cachereplica2
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_data:
    driver: local
