# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_web.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto_web.proto\x12\x06search\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\rSearchResults\x12\x18\n\x03web\x18\x01 \x03(\x0b\x32\x0b.search.Web\"B\n\x03Web\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t2G\n\x06Search\x12=\n\x11GetServerResponse\x12\x0f.search.Message\x1a\x15.search.SearchResults\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_web_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=27
  _MESSAGE._serialized_end=53
  _SEARCHRESULTS._serialized_start=55
  _SEARCHRESULTS._serialized_end=96
  _WEB._serialized_start=98
  _WEB._serialized_end=164
  _SEARCH._serialized_start=166
  _SEARCH._serialized_end=237
# @@protoc_insertion_point(module_scope)
