# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nserv.proto\"\x15\n\x06Search\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x1a\n\x0blanResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2)\n\x03lan\x12\"\n\tgetSearch\x12\x07.Search\x1a\x0c.lanResponseb\x06proto3')



_SEARCH = DESCRIPTOR.message_types_by_name['Search']
_LANRESPONSE = DESCRIPTOR.message_types_by_name['lanResponse']
Search = _reflection.GeneratedProtocolMessageType('Search', (_message.Message,), {
  'DESCRIPTOR' : _SEARCH,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:Search)
  })
_sym_db.RegisterMessage(Search)

lanResponse = _reflection.GeneratedProtocolMessageType('lanResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANRESPONSE,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:lanResponse)
  })
_sym_db.RegisterMessage(lanResponse)

_LAN = DESCRIPTOR.services_by_name['lan']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCH._serialized_start=14
  _SEARCH._serialized_end=35
  _LANRESPONSE._serialized_start=37
  _LANRESPONSE._serialized_end=63
  _LAN._serialized_start=65
  _LAN._serialized_end=106
# @@protoc_insertion_point(module_scope)
