# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serv_pb2 as serv__pb2


class lanStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSearch = channel.unary_unary(
                '/lan/getSearch',
                request_serializer=serv__pb2.Search.SerializeToString,
                response_deserializer=serv__pb2.lanResponse.FromString,
                )


class lanServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_lanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.getSearch,
                    request_deserializer=serv__pb2.Search.FromString,
                    response_serializer=serv__pb2.lanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lan', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class lan(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lan/getSearch',
            serv__pb2.Search.SerializeToString,
            serv__pb2.lanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
