# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nserv.proto\x12\x06search\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\rSearchResults\x12\x18\n\x03web\x18\x01 \x03(\x0b\x32\x0b.search.Web\"B\n\x03Web\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t2G\n\x06Search\x12=\n\x11GetServerResponse\x12\x0f.search.Message\x1a\x15.search.SearchResults\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_SEARCHRESULTS = DESCRIPTOR.message_types_by_name['SearchResults']
_WEB = DESCRIPTOR.message_types_by_name['Web']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:search.Message)
  })
_sym_db.RegisterMessage(Message)

SearchResults = _reflection.GeneratedProtocolMessageType('SearchResults', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESULTS,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:search.SearchResults)
  })
_sym_db.RegisterMessage(SearchResults)

Web = _reflection.GeneratedProtocolMessageType('Web', (_message.Message,), {
  'DESCRIPTOR' : _WEB,
  '__module__' : 'serv_pb2'
  # @@protoc_insertion_point(class_scope:search.Web)
  })
_sym_db.RegisterMessage(Web)

_SEARCH = DESCRIPTOR.services_by_name['Search']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=22
  _MESSAGE._serialized_end=48
  _SEARCHRESULTS._serialized_start=50
  _SEARCHRESULTS._serialized_end=91
  _WEB._serialized_start=93
  _WEB._serialized_end=159
  _SEARCH._serialized_start=161
  _SEARCH._serialized_end=232
# @@protoc_insertion_point(module_scope)
